### ISSUE TITLE
Webpack 5 and HtmlWebpackPlugin 5 support

### ISSUE THREAD

**Issue by sshrshnv** [JoviDeCroock/webpack-module-nomodule-plugin#25]
This plugin doesn't work with webpack v5 and HtmlWebpackPlugin v5.

**Comment by JoviDeCroock** [comment]
Yeah, it doesn't claim to do so https://github.com/JoviDeCroock/webpack-module-nomodule-plugin/blob/main/package.json#L16-L17 haven't really had a lot of active development time when it comes to open-source 😅 feel free to PR if you know the semantics to switch over to support v5.

**Comment by Ge11ert** [comment]
@JoviDeCroock it seems things are not so bad as they could be.

I have updated webpack configuration for one of my projects and now it runs with webpack 5 and html-webpack-plugin 5 accordingly. During all update routines I disabled this plugin and some other stuff to make sure that plain configuration works fine.

So, having this comment from @sh-a-v, I'd spent a couple of hours reading git log of html-webpack-plugin updates to version 5 and investigating any other useful information (cannot complain though). And frankly I was ready to get a bunch of mistakes.
But when I activated this plugin and ran project build there was no errors at all and the output seems to be correct.

So maybe this plugin works in some cases and it doesn't in some other cases. Still need to get all things thoroughly tested but for now it pretends to work as expected

**Comment by Ge11ert** [comment]
@JoviDeCroock 
Here come some news (no quite good) =)

I've got two projects both running webpack 5 + this pluign. One project is fine, and the other is not so lucky as I learned out recently.

I faced a problem with contenthash generation for js-bundles (if chunk output name contains `[contenthash]` placeholder). After build is complete I get the situation, when contenthash of a chunk in `script.src` in html-file differs from contenthash in the actual file placed in dist folder.

So, index.html has smth like that:
```
<script src="/static/vendor.legacy.d8770331569ffa39.js" nomodule></script>
<script src="/static/app.legacy.cd60c1e2bf7c35d4.js" nomodule></script>
```
And dist folder has this:
```
.
└── static
    ├── app.legacy.728846e82162c197.js
    ├── vendor.legacy.19db973067a6c1fd.js
    └── vendor.legacy.19db973067a6c1fd.js.LICENSE.txt
```

I did some research and that's what I found.

In webpack 5, they refactored contenthash generation and now there's an option [optimization.realcontenthash](https://webpack.js.org/configuration/optimization/#optimizationrealcontenthash). The option is activated by default, so webpack calls [RealContentHashPlugin](https://webpack.js.org/plugins/internal-plugins/#realcontenthashplugin), which (re)calculates contenthash of an asset and updates asset info.

As I understand, now webpack calculates hash based on output, not input (there is a [pull request](https://github.com/webpack/webpack/pull/11339), not well documented to be said).

The problem is that RealContentHashPlugin is being applied after all html-webpack-plugin staff done, at the stage PROCESS_ASSETS_STAGE_OPTIMIZE_HASH (see [List of asset processing stages](https://webpack.js.org/api/compilation-hooks/#list-of-asset-processing-stages)). And HtmlWebpackPlugin generates html at the PROCESS_ASSETS_STAGE_OPTIMIZE_INLINE stage, which is earlier.

Webpack is clever and updates html-asset (along with other assets) after hash recalculation, but at this moment we have this temp file `assets-${htmlName}.json` with previous build assets. And this temp file not meant to be updated, it contains assets with old hashes.

When iteration 2 comes, it grabs temp file, but saved assets have wrong (old) contenthash, because it was recalculated in the end of first iteration.

It seems, ad-hoc solution is to disable `realContentHash`, so the hashes won't be recalculated. But at this point we can loose the very meaning of content hash, because
> If realContentHash is set to false, internal data is used to calculate the hash and it can change when assets are identical.

**Comment by thecontrarycat** [comment]
There's also the problem that nothing gets written at all if you don't explicitly set `inject: 'body'` on the `HtmlWebpackPlugin` options as they have changed the default for `scriptLoading` from `blocking` to `defer` which defaults to putting scripts in the head.

**Comment by thecontrarycat** [comment]
@JoviDeCroock  @Ge11ert I have a fix for the rehashing in Webpack 5 by emitting the .json file as an asset in iteration 1, but it will require bumping the minimum Webpack version to 4.40.0.

If that's ok, I'll raise a PR for it.

**Comment by thecontrarycat** [comment]
#30 Includes additional fixes for this issue.

**Comment by sinemacula-ben** [comment]
@Ge11ert - quite late to the party here, but did you find a way to prevent the `assets-${htmlName}.json` from being generated? Or, to word it better, given they are 'temporary' files, can you think of a reason why they are not being deleted? I had another issue in the past with incorrect hashes being generated for certain assets, so I already had my `realContentHash` set to `false`.

I would quite like to prevent these JSON files from clogging up my dist folder without implementing some dirty cleanup plugin...
